repos:
  - repo: local
    hooks:
      - id: ceres-quality-gate
        name: Ceres quality gate
        entry: ./pre-commit.sh
        language: system
        pass_filenames: false
        always_run: true
