"""Robot skill facade classes — auto-generated by tools/gen_robot_skills.py.

Each class represents a robot skill package. Fields are int levels (default 0).
Level-0 means no specialisation yet. Fields above 0 are purchased specialisations,
each counting as one skill package for bandwidth and cost purposes.
"""

from typing import Annotated, ClassVar, Literal

from pydantic import Field

from ceres.character.domain import skills as _char
from ceres.character.domain.characteristics import Chars
from ceres.make.robot._robot_skill_base import _RobotSkill


class Admin(_RobotSkill):
    type: Literal['robot_pkg.Admin'] = 'robot_pkg.Admin'
    _char_cls: ClassVar = _char.Admin
    level: int = 0


class Advocate(_RobotSkill):
    type: Literal['robot_pkg.Advocate'] = 'robot_pkg.Advocate'
    _char_cls: ClassVar = _char.Advocate
    level: int = 0


class Animals(_RobotSkill):
    type: Literal['robot_pkg.Animals'] = 'robot_pkg.Animals'
    _char_cls: ClassVar = _char.Animals
    level: int = 0
    handling: int = 0
    veterinary: int = 0
    training: int = 0


class PerformingArt(_RobotSkill):
    type: Literal['robot_pkg.PerformingArt'] = 'robot_pkg.PerformingArt'
    _char_cls: ClassVar = _char.PerformingArt
    level: int = 0
    performer: int = 0
    instrument: int = 0


class CreativeArt(_RobotSkill):
    type: Literal['robot_pkg.CreativeArt'] = 'robot_pkg.CreativeArt'
    _char_cls: ClassVar = _char.CreativeArt
    level: int = 0
    visual_media: int = 0
    exotic_media: int = 0


class PresentationArt(_RobotSkill):
    type: Literal['robot_pkg.PresentationArt'] = 'robot_pkg.PresentationArt'
    _char_cls: ClassVar = _char.PresentationArt
    level: int = 0
    holography: int = 0
    writing: int = 0


class Astrogation(_RobotSkill):
    type: Literal['robot_pkg.Astrogation'] = 'robot_pkg.Astrogation'
    _char_cls: ClassVar = _char.Astrogation
    level: int = 0


class Athletics(_RobotSkill):
    type: Literal['robot_pkg.Athletics'] = 'robot_pkg.Athletics'
    _char_cls: ClassVar = _char.Athletics
    level: int = 0
    dexterity: int = 0
    endurance: int = 0
    strength: int = 0


class Broker(_RobotSkill):
    type: Literal['robot_pkg.Broker'] = 'robot_pkg.Broker'
    _char_cls: ClassVar = _char.Broker
    level: int = 0


class Carouse(_RobotSkill):
    type: Literal['robot_pkg.Carouse'] = 'robot_pkg.Carouse'
    _char_cls: ClassVar = _char.Carouse
    level: int = 0


class Deception(_RobotSkill):
    type: Literal['robot_pkg.Deception'] = 'robot_pkg.Deception'
    _char_cls: ClassVar = _char.Deception
    level: int = 0


class Diplomat(_RobotSkill):
    type: Literal['robot_pkg.Diplomat'] = 'robot_pkg.Diplomat'
    _char_cls: ClassVar = _char.Diplomat
    level: int = 0


class Drive(_RobotSkill):
    type: Literal['robot_pkg.Drive'] = 'robot_pkg.Drive'
    _char_cls: ClassVar = _char.Drive
    level: int = 0
    hovercraft: int = 0
    mole: int = 0
    track: int = 0
    walker: int = 0
    wheel: int = 0


class Electronics(_RobotSkill):
    type: Literal['robot_pkg.Electronics'] = 'robot_pkg.Electronics'
    _char_cls: ClassVar = _char.Electronics
    level: int = 0
    comms: int = 0
    computers: int = 0
    remote_ops: int = 0
    sensors: int = 0


class Engineer(_RobotSkill):
    type: Literal['robot_pkg.Engineer'] = 'robot_pkg.Engineer'
    _char_cls: ClassVar = _char.Engineer
    level: int = 0
    m_drive: int = 0
    j_drive: int = 0
    life_support: int = 0
    power: int = 0


class Explosives(_RobotSkill):
    type: Literal['robot_pkg.Explosives'] = 'robot_pkg.Explosives'
    _char_cls: ClassVar = _char.Explosives
    level: int = 0


class Flyer(_RobotSkill):
    type: Literal['robot_pkg.Flyer'] = 'robot_pkg.Flyer'
    _char_cls: ClassVar = _char.Flyer
    level: int = 0
    airship: int = 0
    grav: int = 0
    ornithopter: int = 0
    rotor: int = 0
    wing: int = 0


class Gambler(_RobotSkill):
    type: Literal['robot_pkg.Gambler'] = 'robot_pkg.Gambler'
    _char_cls: ClassVar = _char.Gambler
    level: int = 0


class GunCombat(_RobotSkill):
    type: Literal['robot_pkg.GunCombat'] = 'robot_pkg.GunCombat'
    _char_cls: ClassVar = _char.GunCombat
    level: int = 0
    archaic: int = 0
    energy: int = 0
    slug: int = 0


class Gunner(_RobotSkill):
    type: Literal['robot_pkg.Gunner'] = 'robot_pkg.Gunner'
    _char_cls: ClassVar = _char.Gunner
    level: int = 0
    turret: int = 0
    ortillery: int = 0
    screen: int = 0
    capital: int = 0


class HeavyWeapons(_RobotSkill):
    type: Literal['robot_pkg.HeavyWeapons'] = 'robot_pkg.HeavyWeapons'
    _char_cls: ClassVar = _char.HeavyWeapons
    level: int = 0
    artillery: int = 0
    portable: int = 0
    vehicle: int = 0


class Investigate(_RobotSkill):
    type: Literal['robot_pkg.Investigate'] = 'robot_pkg.Investigate'
    _char_cls: ClassVar = _char.Investigate
    level: int = 0


class JackOfAllTrades(_RobotSkill):
    type: Literal['robot_pkg.JackOfAllTrades'] = 'robot_pkg.JackOfAllTrades'
    _char_cls: ClassVar = _char.JackOfAllTrades
    level: int = 0


class LanguageGalanglic(_RobotSkill):
    type: Literal['robot_pkg.LanguageGalanglic'] = 'robot_pkg.LanguageGalanglic'
    _char_cls: ClassVar = _char.LanguageGalanglic
    level: int = 0


class LanguageVilani(_RobotSkill):
    type: Literal['robot_pkg.LanguageVilani'] = 'robot_pkg.LanguageVilani'
    _char_cls: ClassVar = _char.LanguageVilani
    level: int = 0


class LanguageZdetl(_RobotSkill):
    type: Literal['robot_pkg.LanguageZdetl'] = 'robot_pkg.LanguageZdetl'
    _char_cls: ClassVar = _char.LanguageZdetl
    level: int = 0


class LanguageOynprith(_RobotSkill):
    type: Literal['robot_pkg.LanguageOynprith'] = 'robot_pkg.LanguageOynprith'
    _char_cls: ClassVar = _char.LanguageOynprith
    level: int = 0


class LanguageTrokh(_RobotSkill):
    type: Literal['robot_pkg.LanguageTrokh'] = 'robot_pkg.LanguageTrokh'
    _char_cls: ClassVar = _char.LanguageTrokh
    level: int = 0


class LanguageGvegh(_RobotSkill):
    type: Literal['robot_pkg.LanguageGvegh'] = 'robot_pkg.LanguageGvegh'
    _char_cls: ClassVar = _char.LanguageGvegh
    level: int = 0


class LanguageAekhu(_RobotSkill):
    type: Literal['robot_pkg.LanguageAekhu'] = 'robot_pkg.LanguageAekhu'
    _char_cls: ClassVar = _char.LanguageAekhu
    level: int = 0


class LanguageArrghoun(_RobotSkill):
    type: Literal['robot_pkg.LanguageArrghoun'] = 'robot_pkg.LanguageArrghoun'
    _char_cls: ClassVar = _char.LanguageArrghoun
    level: int = 0


class LanguageIrilitok(_RobotSkill):
    type: Literal['robot_pkg.LanguageIrilitok'] = 'robot_pkg.LanguageIrilitok'
    _char_cls: ClassVar = _char.LanguageIrilitok
    level: int = 0


class LanguageLogaksu(_RobotSkill):
    type: Literal['robot_pkg.LanguageLogaksu'] = 'robot_pkg.LanguageLogaksu'
    _char_cls: ClassVar = _char.LanguageLogaksu
    level: int = 0


class LanguageOvaghoun(_RobotSkill):
    type: Literal['robot_pkg.LanguageOvaghoun'] = 'robot_pkg.LanguageOvaghoun'
    _char_cls: ClassVar = _char.LanguageOvaghoun
    level: int = 0


class LanguageSuedzuk(_RobotSkill):
    type: Literal['robot_pkg.LanguageSuedzuk'] = 'robot_pkg.LanguageSuedzuk'
    _char_cls: ClassVar = _char.LanguageSuedzuk
    level: int = 0


class LanguageVuakedh(_RobotSkill):
    type: Literal['robot_pkg.LanguageVuakedh'] = 'robot_pkg.LanguageVuakedh'
    _char_cls: ClassVar = _char.LanguageVuakedh
    level: int = 0


class LanguageSagamaal(_RobotSkill):
    type: Literal['robot_pkg.LanguageSagamaal'] = 'robot_pkg.LanguageSagamaal'
    _char_cls: ClassVar = _char.LanguageSagamaal
    level: int = 0


class LanguageDarrian(_RobotSkill):
    type: Literal['robot_pkg.LanguageDarrian'] = 'robot_pkg.LanguageDarrian'
    _char_cls: ClassVar = _char.LanguageDarrian
    level: int = 0


class Leadership(_RobotSkill):
    type: Literal['robot_pkg.Leadership'] = 'robot_pkg.Leadership'
    _char_cls: ClassVar = _char.Leadership
    level: int = 0


class Mechanic(_RobotSkill):
    type: Literal['robot_pkg.Mechanic'] = 'robot_pkg.Mechanic'
    _char_cls: ClassVar = _char.Mechanic
    level: int = 0


class Medic(_RobotSkill):
    type: Literal['robot_pkg.Medic'] = 'robot_pkg.Medic'
    _char_cls: ClassVar = _char.Medic
    level: int = 0


class Melee(_RobotSkill):
    type: Literal['robot_pkg.Melee'] = 'robot_pkg.Melee'
    _char_cls: ClassVar = _char.Melee
    level: int = 0
    unarmed: int = 0
    blade: int = 0
    bludgeon: int = 0
    natural: int = 0
    grapple: int = 0
    striking: int = 0
    fencing: int = 0


class Navigation(_RobotSkill):
    type: Literal['robot_pkg.Navigation'] = 'robot_pkg.Navigation'
    _char_cls: ClassVar = _char.Navigation
    level: int = 0


class Persuade(_RobotSkill):
    type: Literal['robot_pkg.Persuade'] = 'robot_pkg.Persuade'
    _char_cls: ClassVar = _char.Persuade
    level: int = 0


class Pilot(_RobotSkill):
    type: Literal['robot_pkg.Pilot'] = 'robot_pkg.Pilot'
    _char_cls: ClassVar = _char.Pilot
    level: int = 0
    small_craft: int = 0
    spacecraft: int = 0
    capital_ships: int = 0


class ColonistProfession(_RobotSkill):
    type: Literal['robot_pkg.ColonistProfession'] = 'robot_pkg.ColonistProfession'
    _char_cls: ClassVar = _char.ColonistProfession
    level: int = 0
    farming: int = 0
    ranching: int = 0


class FreeloaderProfession(_RobotSkill):
    type: Literal['robot_pkg.FreeloaderProfession'] = 'robot_pkg.FreeloaderProfession'
    _char_cls: ClassVar = _char.FreeloaderProfession
    level: int = 0
    scrounging: int = 0
    security: int = 0


class HostileEnvironmentProfession(_RobotSkill):
    type: Literal['robot_pkg.HostileEnvironmentProfession'] = 'robot_pkg.HostileEnvironmentProfession'
    _char_cls: ClassVar = _char.HostileEnvironmentProfession
    level: int = 0
    contaminant: int = 0
    low_g: int = 0
    high_g: int = 0
    underwater: int = 0


class SpacerProfession(_RobotSkill):
    type: Literal['robot_pkg.SpacerProfession'] = 'robot_pkg.SpacerProfession'
    _char_cls: ClassVar = _char.SpacerProfession
    level: int = 0
    belter: int = 0
    crewmember: int = 0


class SportProfession(_RobotSkill):
    type: Literal['robot_pkg.SportProfession'] = 'robot_pkg.SportProfession'
    _char_cls: ClassVar = _char.SportProfession
    level: int = 0
    atmosphere_surfing: int = 0
    golf: int = 0
    motorsports: int = 0
    racquet_sports: int = 0
    team_ball_sports: int = 0
    track_and_field: int = 0


class WorkerProfession(_RobotSkill):
    type: Literal['robot_pkg.WorkerProfession'] = 'robot_pkg.WorkerProfession'
    _char_cls: ClassVar = _char.WorkerProfession
    level: int = 0
    armourer: int = 0
    biologicals: int = 0
    civil_engineering: int = 0
    construction: int = 0
    hydroponics: int = 0
    metalworking: int = 0
    polymers: int = 0


class Recon(_RobotSkill):
    type: Literal['robot_pkg.Recon'] = 'robot_pkg.Recon'
    _char_cls: ClassVar = _char.Recon
    level: int = 0


class LifeScience(_RobotSkill):
    type: Literal['robot_pkg.LifeScience'] = 'robot_pkg.LifeScience'
    _char_cls: ClassVar = _char.LifeScience
    level: int = 0
    biology: int = 0
    genetics: int = 0
    psionicology: int = 0
    xenology: int = 0


class PhysicalScience(_RobotSkill):
    type: Literal['robot_pkg.PhysicalScience'] = 'robot_pkg.PhysicalScience'
    _char_cls: ClassVar = _char.PhysicalScience
    level: int = 0
    chemistry: int = 0
    physics: int = 0
    jumpspace_physics: int = 0


class RoboticScience(_RobotSkill):
    type: Literal['robot_pkg.RoboticScience'] = 'robot_pkg.RoboticScience'
    _char_cls: ClassVar = _char.RoboticScience
    level: int = 0
    cybernetics: int = 0
    robotics: int = 0


class SocialScience(_RobotSkill):
    type: Literal['robot_pkg.SocialScience'] = 'robot_pkg.SocialScience'
    _char_cls: ClassVar = _char.SocialScience
    level: int = 0
    archaeology: int = 0
    economics: int = 0
    history: int = 0
    linguistics: int = 0
    philosophy: int = 0
    psychology: int = 0
    sophontology: int = 0


class SpaceScience(_RobotSkill):
    type: Literal['robot_pkg.SpaceScience'] = 'robot_pkg.SpaceScience'
    _char_cls: ClassVar = _char.SpaceScience
    level: int = 0
    astronomy: int = 0
    cosmology: int = 0
    planetology: int = 0


class Seafarer(_RobotSkill):
    type: Literal['robot_pkg.Seafarer'] = 'robot_pkg.Seafarer'
    _char_cls: ClassVar = _char.Seafarer
    level: int = 0
    ocean_ships: int = 0
    personal: int = 0
    sail: int = 0
    submarine: int = 0


class Stealth(_RobotSkill):
    type: Literal['robot_pkg.Stealth'] = 'robot_pkg.Stealth'
    _char_cls: ClassVar = _char.Stealth
    level: int = 0


class Steward(_RobotSkill):
    type: Literal['robot_pkg.Steward'] = 'robot_pkg.Steward'
    _char_cls: ClassVar = _char.Steward
    level: int = 0


class Streetwise(_RobotSkill):
    type: Literal['robot_pkg.Streetwise'] = 'robot_pkg.Streetwise'
    _char_cls: ClassVar = _char.Streetwise
    level: int = 0


class Survival(_RobotSkill):
    type: Literal['robot_pkg.Survival'] = 'robot_pkg.Survival'
    _char_cls: ClassVar = _char.Survival
    level: int = 0


class Tactics(_RobotSkill):
    type: Literal['robot_pkg.Tactics'] = 'robot_pkg.Tactics'
    _char_cls: ClassVar = _char.Tactics
    level: int = 0
    military: int = 0
    naval: int = 0


class VaccSuit(_RobotSkill):
    type: Literal['robot_pkg.VaccSuit'] = 'robot_pkg.VaccSuit'
    _char_cls: ClassVar = _char.VaccSuit
    level: int = 0


_ROBOT_PROFESSION_SPEC_LABELS: dict[str, str] = {
    'belter': 'Belter',
    'cleaning': 'Cleaning',
    'domestic_cleaner': 'Domestic Cleaner',
    'domestic_servant': 'Domestic Servant',
    'fabricator': 'Fabricator',
    'gardening': 'Gardening',
    'labourer': 'Labourer',
    'robotics': 'Robotics',
}


class RobotProfession(_RobotSkill):
    """Robot-specific profession skill with no character domain equivalent."""

    type: Literal['robot_pkg.RobotProfession'] = 'robot_pkg.RobotProfession'
    _char_cls: ClassVar = None  # type: ignore[assignment]
    belter: int = 0
    cleaning: int = 0
    domestic_cleaner: int = 0
    domestic_servant: int = 0
    fabricator: int = 0
    gardening: int = 0
    labourer: int = 0
    robotics: int = 0

    @classmethod
    def skill_name(cls) -> str:
        return 'Profession'

    @property
    def tl(self) -> int:
        return 9

    @property
    def bandwidth(self) -> int:
        active = self._active_fields()
        return sum(lvl for _, lvl in active) if active else 0

    @property
    def cost(self) -> float:
        active = self._active_fields()
        return sum(200.0 * (10.0**lvl) for _, lvl in active) if active else 200.0

    def display_entries(self, dms: dict[Chars, int]) -> dict[str, int]:
        active = self._active_fields()
        dm = dms.get(Chars.INT, 0)
        if not active:
            return {self.skill_name(): 0}
        return {
            f'{self.skill_name()} ({_ROBOT_PROFESSION_SPEC_LABELS.get(f, f)})': max(0, lvl + dm) for f, lvl in active
        }


AnyRobotSkill = Annotated[
    Admin
    | Advocate
    | Animals
    | PerformingArt
    | CreativeArt
    | PresentationArt
    | Astrogation
    | Athletics
    | Broker
    | Carouse
    | Deception
    | Diplomat
    | Drive
    | Electronics
    | Engineer
    | Explosives
    | Flyer
    | Gambler
    | GunCombat
    | Gunner
    | HeavyWeapons
    | Investigate
    | JackOfAllTrades
    | LanguageGalanglic
    | LanguageVilani
    | LanguageZdetl
    | LanguageOynprith
    | LanguageTrokh
    | LanguageGvegh
    | LanguageAekhu
    | LanguageArrghoun
    | LanguageIrilitok
    | LanguageLogaksu
    | LanguageOvaghoun
    | LanguageSuedzuk
    | LanguageVuakedh
    | LanguageSagamaal
    | LanguageDarrian
    | Leadership
    | Mechanic
    | Medic
    | Melee
    | Navigation
    | Persuade
    | Pilot
    | ColonistProfession
    | FreeloaderProfession
    | HostileEnvironmentProfession
    | SpacerProfession
    | SportProfession
    | WorkerProfession
    | Recon
    | LifeScience
    | PhysicalScience
    | RoboticScience
    | SocialScience
    | SpaceScience
    | Seafarer
    | Stealth
    | Steward
    | Streetwise
    | Survival
    | Tactics
    | VaccSuit
    | RobotProfession,
    Field(discriminator='type'),
]
