#!/bin/bash
uv run pytest --cov --cov-branch tests/unit/test___init__.py | grep src/ceres/__init__.py
uv run pytest --cov --cov-branch tests/unit/adapters/test_travellermap.py | grep src/ceres/adapters/travellermap.py
uv run pytest --cov --cov-branch tests/unit/character/test___init__.py | grep src/ceres/character/__init__.py
uv run pytest --cov --cov-branch tests/unit/character/domain/test_benefits.py | grep src/ceres/character/domain/benefits.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test___init__.py | grep src/ceres/character/domain/career/__init__.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_advancement.py | grep src/ceres/character/domain/career/advancement.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_agent.py | grep src/ceres/character/domain/career/agent.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_army.py | grep src/ceres/character/domain/career/army.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_career_data.py | grep src/ceres/character/domain/career/career_data.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_career_events.py | grep src/ceres/character/domain/career/career_events.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_citizen.py | grep src/ceres/character/domain/career/citizen.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_common.py | grep src/ceres/character/domain/career/common.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_common_pending.py | grep src/ceres/character/domain/career/common_pending.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_draft.py | grep src/ceres/character/domain/career/draft.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_drifter.py | grep src/ceres/character/domain/career/drifter.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_entertainer.py | grep src/ceres/character/domain/career/entertainer.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_entry.py | grep src/ceres/character/domain/career/entry.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_loader.py | grep src/ceres/character/domain/career/loader.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_marines.py | grep src/ceres/character/domain/career/marines.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_merchant.py | grep src/ceres/character/domain/career/merchant.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_muster_out.py | grep src/ceres/character/domain/career/muster_out.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_navy.py | grep src/ceres/character/domain/career/navy.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_noble.py | grep src/ceres/character/domain/career/noble.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_prisoner.py | grep src/ceres/character/domain/career/prisoner.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_prisoner_events.py | grep src/ceres/character/domain/career/prisoner_events.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_psion.py | grep src/ceres/character/domain/career/psion.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_rogue.py | grep src/ceres/character/domain/career/rogue.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_scholar.py | grep src/ceres/character/domain/career/scholar.py
uv run pytest --cov --cov-branch tests/unit/character/domain/career/test_scout.py | grep src/ceres/character/domain/career/scout.py
uv run pytest --cov --cov-branch tests/unit/character/domain/test_character_start.py | grep src/ceres/character/domain/character_start.py
uv run pytest --cov --cov-branch tests/unit/character/domain/test_character_state.py | grep src/ceres/character/domain/character_state.py
uv run pytest --cov --cov-branch tests/unit/character/domain/test_characteristics.py | grep src/ceres/character/domain/characteristics.py
uv run pytest --cov --cov-branch tests/unit/character/domain/test_choice_events.py | grep src/ceres/character/domain/choice_events.py
uv run pytest --cov --cov-branch tests/unit/character/domain/test_connection.py | grep src/ceres/character/domain/connection.py
uv run pytest --cov --cov-branch tests/unit/character/domain/test_connection_events.py | grep src/ceres/character/domain/connection_events.py
uv run pytest --cov --cov-branch tests/unit/character/domain/test_dice.py | grep src/ceres/character/domain/dice.py
uv run pytest --cov --cov-branch tests/unit/character/domain/test_event_handlers.py | grep src/ceres/character/domain/event_handlers.py
uv run pytest --cov --cov-branch tests/unit/character/domain/health/test_health_events.py | grep src/ceres/character/domain/health/health_events.py
uv run pytest --cov --cov-branch tests/unit/character/domain/homeworld/test_homeworld_events.py | grep src/ceres/character/domain/homeworld/homeworld_events.py
uv run pytest --cov --cov-branch tests/unit/character/domain/test_life_events.py | grep src/ceres/character/domain/life_events.py
uv run pytest --cov --cov-branch tests/unit/character/domain/precareer/test_colonial_upbringing.py | grep src/ceres/character/domain/precareer/colonial_upbringing.py
uv run pytest --cov --cov-branch tests/unit/character/domain/precareer/test_loader.py | grep src/ceres/character/domain/precareer/loader.py
uv run pytest --cov --cov-branch tests/unit/character/domain/precareer/test_merchant_academy.py | grep src/ceres/character/domain/precareer/merchant_academy.py
uv run pytest --cov --cov-branch tests/unit/character/domain/precareer/test_military_academy.py | grep src/ceres/character/domain/precareer/military_academy.py
uv run pytest --cov --cov-branch tests/unit/character/domain/precareer/test_precareer_data.py | grep src/ceres/character/domain/precareer/precareer_data.py
uv run pytest --cov --cov-branch tests/unit/character/domain/precareer/test_precareer_events.py | grep src/ceres/character/domain/precareer/precareer_events.py
uv run pytest --cov --cov-branch tests/unit/character/domain/precareer/test_psionic_community.py | grep src/ceres/character/domain/precareer/psionic_community.py
uv run pytest --cov --cov-branch tests/unit/character/domain/precareer/test_school_of_hard_knocks.py | grep src/ceres/character/domain/precareer/school_of_hard_knocks.py
uv run pytest --cov --cov-branch tests/unit/character/domain/precareer/test_spacer_community.py | grep src/ceres/character/domain/precareer/spacer_community.py
uv run pytest --cov --cov-branch tests/unit/character/domain/precareer/test_university.py | grep src/ceres/character/domain/precareer/university.py
uv run pytest --cov --cov-branch tests/unit/character/domain/test_psionics.py | grep src/ceres/character/domain/psionics.py
uv run pytest --cov --cov-branch tests/unit/character/domain/test_skill_events.py | grep src/ceres/character/domain/skill_events.py
uv run pytest --cov --cov-branch tests/unit/character/domain/test_skills.py | grep src/ceres/character/domain/skills.py
uv run pytest --cov --cov-branch tests/unit/character/domain/sophont/test___init__.py | grep src/ceres/character/domain/sophont/__init__.py
uv run pytest --cov --cov-branch tests/unit/character/domain/sophont/test_humaniti.py | grep src/ceres/character/domain/sophont/humaniti.py
uv run pytest --cov --cov-branch tests/unit/character/domain/test_spec.py | grep src/ceres/character/domain/spec.py
uv run pytest --cov --cov-branch tests/unit/character/domain/test_term_data.py | grep src/ceres/character/domain/term_data.py
uv run pytest --cov --cov-branch tests/unit/character/test_input_specs.py | grep src/ceres/character/input_specs.py
uv run pytest --cov --cov-branch tests/unit/character/mechanism/test_errors.py | grep src/ceres/character/mechanism/errors.py
uv run pytest --cov --cov-branch tests/unit/character/mechanism/test_event_base.py | grep src/ceres/character/mechanism/event_base.py
uv run pytest --cov --cov-branch tests/unit/character/mechanism/test_pending_input.py | grep src/ceres/character/mechanism/pending_input.py
uv run pytest --cov --cov-branch tests/unit/character/mechanism/test_replay.py | grep src/ceres/character/mechanism/replay.py
uv run pytest --cov --cov-branch tests/unit/character/mechanism/test_store.py | grep src/ceres/character/mechanism/store.py
uv run pytest --cov --cov-branch tests/unit/character/test_notes.py | grep src/ceres/character/notes.py
uv run pytest --cov --cov-branch tests/unit/character/test_report.py | grep src/ceres/character/report.py
uv run pytest --cov --cov-branch tests/unit/character/web/test_app.py | grep src/ceres/character/web/app.py
uv run pytest --cov --cov-branch tests/unit/character/web/test_routes.py | grep src/ceres/character/web/routes.py
uv run pytest --cov --cov-branch tests/unit/gear/test_catalog.py | grep src/ceres/gear/catalog.py
uv run pytest --cov --cov-branch tests/unit/gear/test_comm.py | grep src/ceres/gear/comm.py
uv run pytest --cov --cov-branch tests/unit/gear/test_computer.py | grep src/ceres/gear/computer.py
uv run pytest --cov --cov-branch tests/unit/gear/test_skill_keys.py | grep src/ceres/gear/skill_keys.py
uv run pytest --cov --cov-branch tests/unit/gear/test_software.py | grep src/ceres/gear/software.py
uv run pytest --cov --cov-branch tests/unit/make/test___init__.py | grep src/ceres/make/__init__.py
uv run pytest --cov --cov-branch tests/unit/make/robot/test___init__.py | grep src/ceres/make/robot/__init__.py
uv run pytest --cov --cov-branch tests/unit/make/robot/test__facades.py | grep src/ceres/make/robot/_facades.py
uv run pytest --cov --cov-branch tests/unit/make/robot/test__robot_skill_base.py | grep src/ceres/make/robot/_robot_skill_base.py
uv run pytest --cov --cov-branch tests/unit/make/robot/test_base.py | grep src/ceres/make/robot/base.py
uv run pytest --cov --cov-branch tests/unit/make/robot/test_brain.py | grep src/ceres/make/robot/brain.py
uv run pytest --cov --cov-branch tests/unit/make/robot/test_chassis.py | grep src/ceres/make/robot/chassis.py
uv run pytest --cov --cov-branch tests/unit/make/robot/test_locomotion.py | grep src/ceres/make/robot/locomotion.py
uv run pytest --cov --cov-branch tests/unit/make/robot/test_manipulators.py | grep src/ceres/make/robot/manipulators.py
uv run pytest --cov --cov-branch tests/unit/make/robot/test_options.py | grep src/ceres/make/robot/options.py
uv run pytest --cov --cov-branch tests/unit/make/robot/test_parts.py | grep src/ceres/make/robot/parts.py
uv run pytest --cov --cov-branch tests/unit/make/robot/test_report.py | grep src/ceres/make/robot/report.py
uv run pytest --cov --cov-branch tests/unit/make/robot/test_robot.py | grep src/ceres/make/robot/robot.py
uv run pytest --cov --cov-branch tests/unit/make/robot/test_skills.py | grep src/ceres/make/robot/skills.py
uv run pytest --cov --cov-branch tests/unit/make/robot/test_spec.py | grep src/ceres/make/robot/spec.py
uv run pytest --cov --cov-branch tests/unit/make/robot/test_text.py | grep src/ceres/make/robot/text.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test___init__.py | grep src/ceres/make/ship/__init__.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_armour.py | grep src/ceres/make/ship/armour.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_automation.py | grep src/ceres/make/ship/automation.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_base.py | grep src/ceres/make/ship/base.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_bridge.py | grep src/ceres/make/ship/bridge.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_catalog.py | grep src/ceres/make/ship/catalog.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_computer.py | grep src/ceres/make/ship/computer.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_crafts.py | grep src/ceres/make/ship/crafts.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_crew.py | grep src/ceres/make/ship/crew.py
uv run pytest --cov --cov-branch tests/unit/make/ship/drives/test___init__.py | grep src/ceres/make/ship/drives/__init__.py
uv run pytest --cov --cov-branch tests/unit/make/ship/drives/test_spinext.py | grep src/ceres/make/ship/drives/spinext.py
uv run pytest --cov --cov-branch tests/unit/make/ship/drives/test_standard.py | grep src/ceres/make/ship/drives/standard.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_expense.py | grep src/ceres/make/ship/expense.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_habitation.py | grep src/ceres/make/ship/habitation.py
uv run pytest --cov --cov-branch tests/unit/make/ship/hull/test___init__.py | grep src/ceres/make/ship/hull/__init__.py
uv run pytest --cov --cov-branch tests/unit/make/ship/hull/test_spinext.py | grep src/ceres/make/ship/hull/spinext.py
uv run pytest --cov --cov-branch tests/unit/make/ship/hull/test_standard.py | grep src/ceres/make/ship/hull/standard.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_occupants.py | grep src/ceres/make/ship/occupants.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_parts.py | grep src/ceres/make/ship/parts.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_power.py | grep src/ceres/make/ship/power.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_report.py | grep src/ceres/make/ship/report.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_screens.py | grep src/ceres/make/ship/screens.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_sensors.py | grep src/ceres/make/ship/sensors.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_ship.py | grep src/ceres/make/ship/ship.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_software.py | grep src/ceres/make/ship/software.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_spec.py | grep src/ceres/make/ship/spec.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_storage.py | grep src/ceres/make/ship/storage.py
uv run pytest --cov --cov-branch tests/unit/make/ship/systems/test___init__.py | grep src/ceres/make/ship/systems/__init__.py
uv run pytest --cov --cov-branch tests/unit/make/ship/systems/test_acceleration.py | grep src/ceres/make/ship/systems/acceleration.py
uv run pytest --cov --cov-branch tests/unit/make/ship/systems/test_access.py | grep src/ceres/make/ship/systems/access.py
uv run pytest --cov --cov-branch tests/unit/make/ship/systems/test_advanced.py | grep src/ceres/make/ship/systems/advanced.py
uv run pytest --cov --cov-branch tests/unit/make/ship/systems/test_command.py | grep src/ceres/make/ship/systems/command.py
uv run pytest --cov --cov-branch tests/unit/make/ship/systems/test_common.py | grep src/ceres/make/ship/systems/common.py
uv run pytest --cov --cov-branch tests/unit/make/ship/systems/test_common_areas.py | grep src/ceres/make/ship/systems/common_areas.py
uv run pytest --cov --cov-branch tests/unit/make/ship/systems/test_drones.py | grep src/ceres/make/ship/systems/drones.py
uv run pytest --cov --cov-branch tests/unit/make/ship/systems/test_external.py | grep src/ceres/make/ship/systems/external.py
uv run pytest --cov --cov-branch tests/unit/make/ship/systems/test_facilities.py | grep src/ceres/make/ship/systems/facilities.py
uv run pytest --cov --cov-branch tests/unit/make/ship/systems/test_logistics.py | grep src/ceres/make/ship/systems/logistics.py
uv run pytest --cov --cov-branch tests/unit/make/ship/systems/test_medical.py | grep src/ceres/make/ship/systems/medical.py
uv run pytest --cov --cov-branch tests/unit/make/ship/systems/test_reentry.py | grep src/ceres/make/ship/systems/reentry.py
uv run pytest --cov --cov-branch tests/unit/make/ship/systems/test_section.py | grep src/ceres/make/ship/systems/section.py
uv run pytest --cov --cov-branch tests/unit/make/ship/systems/test_security.py | grep src/ceres/make/ship/systems/security.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_text.py | grep src/ceres/make/ship/text.py
uv run pytest --cov --cov-branch tests/unit/make/ship/test_view.py | grep src/ceres/make/ship/view.py
uv run pytest --cov --cov-branch tests/unit/make/ship/weapons/test___init__.py | grep src/ceres/make/ship/weapons/__init__.py
uv run pytest --cov --cov-branch tests/unit/make/ship/weapons/test_barbettes.py | grep src/ceres/make/ship/weapons/barbettes.py
uv run pytest --cov --cov-branch tests/unit/make/ship/weapons/test_bays.py | grep src/ceres/make/ship/weapons/bays.py
uv run pytest --cov --cov-branch tests/unit/make/ship/weapons/test_common.py | grep src/ceres/make/ship/weapons/common.py
uv run pytest --cov --cov-branch tests/unit/make/ship/weapons/test_magazines.py | grep src/ceres/make/ship/weapons/magazines.py
uv run pytest --cov --cov-branch tests/unit/make/ship/weapons/test_mounts.py | grep src/ceres/make/ship/weapons/mounts.py
uv run pytest --cov --cov-branch tests/unit/make/ship/weapons/test_point_defense.py | grep src/ceres/make/ship/weapons/point_defense.py
uv run pytest --cov --cov-branch tests/unit/make/ship/weapons/test_section.py | grep src/ceres/make/ship/weapons/section.py
uv run pytest --cov --cov-branch tests/unit/make/ship/weapons/test_spinal.py | grep src/ceres/make/ship/weapons/spinal.py
uv run pytest --cov --cov-branch tests/unit/report/test___init__.py | grep src/ceres/report/__init__.py
uv run pytest --cov --cov-branch tests/unit/report/test_render.py | grep src/ceres/report/render.py
uv run pytest --cov --cov-branch tests/unit/test_settings.py | grep src/ceres/settings.py
uv run pytest --cov --cov-branch tests/unit/test_shared.py | grep src/ceres/shared.py
uv run pytest --cov --cov-branch tests/unit/worlds/test___init__.py | grep src/ceres/worlds/__init__.py
uv run pytest --cov --cov-branch tests/unit/worlds/test_sector_filters.py | grep src/ceres/worlds/sector_filters.py
