/// <reference types="vitest/config" />
import { playwright } from '@vitest/browser-playwright';
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [sveltekit()],
  // Rolldown prints a plugin-timing breakdown on every build; useful when
  // profiling, noise in a pre-commit gate.
  build: { rollupOptions: { checks: { pluginTimings: false } } },
  test: {
    /**
     * Two suites, split by what they need rather than by what they cover.
     *
     * `rules` is the domain layer: pure functions over plain data, no DOM, so
     * it runs in Node in milliseconds and is the suite to keep large.
     *
     * `components` renders Svelte in a real Chromium. jsdom was the cheaper
     * option and would have been the wrong one: every UI defect worth catching
     * here has been a layout or a third-party-grid defect, and jsdom has no
     * layout engine and does not run the grid's virtualisation.
     */
    projects: [
      {
        extends: true,
        test: {
          name: 'rules',
          include: ['src/**/*.test.ts'],
          exclude: ['src/**/*.svelte.test.ts'],
          environment: 'node',
        },
      },
      {
        extends: true,
        test: {
          name: 'components',
          include: ['src/**/*.svelte.test.ts'],
          browser: {
            enabled: true,
            provider: playwright(),
            headless: true,
            // A desktop viewport. The default is narrow enough that the grid
            // virtualises its right-hand columns away and its own scrollbar
            // covers the cells, which fails tests for reasons that have
            // nothing to do with the component.
            viewport: { width: 1280, height: 900 },
            instances: [{ browser: 'chromium' }],
          },
        },
      },
    ],
    coverage: {
      provider: 'v8',
      include: ['src/lib/**'],
      // Generated by SvelteKit, and the route files are thin wiring over the
      // library code the suites do cover.
      exclude: ['src/**/*.test.ts', 'src/**/*.d.ts'],
      reporter: ['text-summary', 'html'],
    },
  },
});
