"""Generator for robot skill facade classes in ceres.make.robot.skills.

Run as: uv run python -m tools.gen_robot_skills
"""

from ceres.character.domain.skills import AnySkill, Skill, _skill_classes, level_fields


def _concrete_char_skills() -> list[type[Skill]]:
    """All concrete Skill subclasses from the AnySkill union."""
    return list(_skill_classes(AnySkill))


_DISCRIMINATOR_PREFIX = 'robot_pkg.'


def generate_facade_class(char_skill_cls: type[Skill]) -> str:
    name = char_skill_cls.__name__
    disc = f'{_DISCRIMINATOR_PREFIX}{name}'
    fields = level_fields(char_skill_cls)
    lines = [
        f'class {name}(_RobotSkill):',
        f"    kind: Literal['{disc}'] = '{disc}'",
        f'    _char_cls: ClassVar = _char.{name}',
    ]
    if fields:
        lines.append('    level: int = 0')
    lines.extend(f'    {field_name}: int = 0' for field_name in fields if field_name != 'level')
    return '\n'.join(lines)


_STATIC_HEADER = '''\
"""Robot skill facade classes — auto-generated by tools/gen_robot_skills.py.

Each class represents a robot skill package. Fields are int levels (default 0).
Level-0 means no specialisation yet. Fields above 0 are purchased specialisations,
each counting as one skill package for bandwidth and cost purposes.
"""

from typing import Annotated, ClassVar, Literal

from pydantic import Field

from ceres.character.domain import skills as _char
from ceres.character.domain.characteristics import Chars
from ceres.make.robot._robot_skill_base import _RobotSkill


'''

_STATIC_ROBOT_PROFESSION = '''


_ROBOT_PROFESSION_SPEC_LABELS: dict[str, str] = {
    'belter': 'Belter',
    'cleaning': 'Cleaning',
    'domestic_cleaner': 'Domestic Cleaner',
    'domestic_servant': 'Domestic Servant',
    'fabricator': 'Fabricator',
    'gardening': 'Gardening',
    'labourer': 'Labourer',
    'robotics': 'Robotics',
}


class RobotProfession(_RobotSkill):
    """Robot-specific profession skill with no character domain equivalent."""

    kind: Literal['robot_pkg.RobotProfession'] = 'robot_pkg.RobotProfession'
    _char_cls: ClassVar = None  # type: ignore[assignment]
    belter: int = 0
    cleaning: int = 0
    domestic_cleaner: int = 0
    domestic_servant: int = 0
    fabricator: int = 0
    gardening: int = 0
    labourer: int = 0
    robotics: int = 0

    @classmethod
    def skill_name(cls) -> str:
        return 'Profession'

    @property
    def tl(self) -> int:
        return 9

    @property
    def bandwidth(self) -> int:
        active = self._active_fields()
        return sum(lvl for _, lvl in active) if active else 0

    @property
    def cost(self) -> float:
        active = self._active_fields()
        return sum(200.0 * (10.0**lvl) for _, lvl in active) if active else 200.0

    def display_entries(self, dms: dict[Chars, int]) -> dict[str, int]:
        active = self._active_fields()
        dm = dms.get(Chars.INT, 0)
        if not active:
            return {self.skill_name(): 0}
        return {
            f'{self.skill_name()} ({_ROBOT_PROFESSION_SPEC_LABELS.get(f, f)})': max(0, lvl + dm) for f, lvl in active
        }
'''


def _union_trailer(class_names: list[str]) -> str:
    union_lines = '\n    | '.join([*class_names, 'RobotProfession'])
    return f"\n\nAnyRobotSkill = Annotated[\n    {union_lines},\n    Field(discriminator='kind'),\n]\n"


def generate_module() -> str:
    char_skills = _concrete_char_skills()
    class_names = [cls.__name__ for cls in char_skills]
    classes = [generate_facade_class(cls) for cls in char_skills]
    return _STATIC_HEADER + '\n\n\n'.join(classes) + _STATIC_ROBOT_PROFESSION + _union_trailer(class_names)


if __name__ == '__main__':
    import os
    from pathlib import Path
    import sys
    import tempfile

    if len(sys.argv) > 1:
        target = Path(sys.argv[1])
    else:
        # Safe default: write to a temp file so running without args never overwrites source
        fd, tmp_name = tempfile.mkstemp(suffix='_facades.py')
        os.close(fd)
        target = Path(tmp_name)
        print('(no path given — writing to temp file; pass src/ceres/make/robot/_facades.py to update source)')

    target.write_text(generate_module(), encoding='utf-8')
    print(f'Written to {target}')
